url: https://pbhavsar.github.io

# Site settings
title: Paavan Bhavsar
description: "Personal site for Paavan Bhavsar"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: ffa300
  secondary: e87e0c
  secondary-dark: 333

# Team names, titles and social links
people:
- name: Paavan Bhavsar
  pic: 1
  position: Software Engineer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: github
    url: http://github.com/pbhavsar

# Build settings
markdown: kramdown
permalink: pretty
